### ISSUE TITLE
ToDo Webseite LSWT2019

### ISSUE THREAD

**Issue by SandraBartsch** [AKSW/lswt2019.aksw.org#1]
**→ TODO Sandra/Natanael bis 7.2.19**
Webseite:
- ~Organisationsteam unterteilen nach Zuständigkeiten (Bsp. Veranstalter - Eccenca&InfAI / Studentenprogramm - Htwk&Köthen&eventuell noch Brandenburg etc.)~ --> #5
- ~Logos der Veranstalter (Eccenca/InfAI) --> #7~ und ~Bilder aller Personen einpflegen~ --> #8
~Affiliation der Orga-Leute hinzu - Natanael und Julia: InfAI-Affiliation schreiben (Uni/dbpedia weg)~ --> #3
--> ~DBpedia als assoziierten Partner angeben~ --> #4
- ~Leere Programmtabelle online setzen und dann nach und nach füllen
 und generell --> Webseite aufhübschen!~  --> #2 

Wenn ich dir helfen/zuarbeiten oder was abnehmen kann, gib mir bescheid. Ich belese mich gern auch zu Turtle ;-) (Sandra)

**Comment by white-gecko** [comment]
Eigentlich brauchst du nur die Datei verstehen und anpassen: https://github.com/AKSW/lswt2019.aksw.org/blob/master/index.html

**Comment by white-gecko** [comment]
Ich habe bootstrap (https://getbootstrap.com/) eingebunden damit können wir die meisten Layoutsachen erledigen: https://getbootstrap.com/docs/4.1/components/card/
Weitere CSS Sachen müssen wir dann hier definieren: https://github.com/AKSW/lswt2019.aksw.org/blob/master/src/_custom.scss

**Comment by SandraBartsch** [comment]
Hm ok...ich schau mir das mal an.
Kannst du mir dann noch das aktuelle Logo vom LSWT2019 und auch gern schon die Flyervorlage im pdf zusenden?!? ich brauch das Logo für das Ticketsystem. Danke!

**Comment by SandraBartsch** [comment]
Ich würde die goldene Mitte wählen, die beinhaltet ja auch eins und drei :)

**Comment by white-gecko** [comment]
![lswt2019-logo_weis svg](https://user-images.githubusercontent.com/1018168/52126514-d62b6f80-262f-11e9-93d1-8058ded3580d.png)
[lswt2019-logo_weis svg.png](https://user-images.githubusercontent.com/1018168/52126514-d62b6f80-262f-11e9-93d1-8058ded3580d.png)
[lswt2019-logo svg.png](https://user-images.githubusercontent.com/1018168/52126515-d62b6f80-262f-11e9-9000-4b204d1f2085.png)
[LSWT2019-Logo.pdf](https://github.com/AKSW/lswt2019.aksw.org/files/2821787/LSWT2019-Logo.pdf)
