### ISSUE TITLE
Leistungsempfänger unklar

### ISSUE THREAD

**Issue by seebi** [AKSW/lswt2019.aksw.org#12]
Die Bezeichnung Leistungsempfänger bei der Bestellung des Tickets ist unklar.
Was soll da rein? Vielleicht kann man das Feld besser beschreiben?
Vielleicht reicht schon ein "Leistungsempfänger (Optional)" :-)

<img width="1157" alt="screenshot 2019-03-04 at 20 42 11" src="https://user-images.githubusercontent.com/510452/53758458-1182bd80-3ebe-11e9-9a62-c1f1f1981861.png">

**Comment by SandraBartsch** [comment]
Der Leistungsempfänger soll eigentlich nur abgefragt werden, falls er abweicht. Aber ich habe das jetzt rausgenommen, ich hoffe das passt jetzt.
