### ISSUE TITLE
Datenschutzerklärung

### ISSUE THREAD

**Issue by SandraBartsch** [AKSW/lswt2019.aksw.org#19]
Bekommen wir das vielleicht hinter einem Link auf der Seite Technik/Impressum versteckt?

**Comment by white-gecko** [comment]
Ich glaub nicht, dass wir das mehr verstecken sollten. Es geht bei der DSGVO um Transparenz.

**Comment by SandraBartsch** [comment]
Dann muss die seite wenigstens aufgehübscht werden. :)
