### ISSUE TITLE
personal images should be squared not circled

### ISSUE THREAD

**Issue by seebi** [AKSW/lswt2019.aksw.org#20]
its easier to produce ...

**Comment by seebi** [comment]
(decided in the todays call)

**Comment by white-gecko** [comment]
@SandraBartsch could you please provide me with the square/rectangular images?

**Comment by SandraBartsch** [comment]
in progress...

**Comment by SandraBartsch** [comment]
![SandraBartsch](https://user-images.githubusercontent.com/17157860/54743704-2dc47100-4bc5-11e9-9d90-70dd6c21bc44.png)
![SebastianTramp](https://user-images.githubusercontent.com/17157860/54743705-2dc47100-4bc5-11e9-97f5-1611e7f47fdc.png)
![ThomasRiechert](https://user-images.githubusercontent.com/17157860/54743706-2e5d0780-4bc5-11e9-97f8-1d29a0f5ee00.png)
![EdgradMarx](https://user-images.githubusercontent.com/17157860/54743707-2e5d0780-4bc5-11e9-9056-f336952f43d8.png)
![JuliaHolze](https://user-images.githubusercontent.com/17157860/54743708-2e5d0780-4bc5-11e9-84cc-24e5d342a1dd.png)
![MichaelMartin](https://user-images.githubusercontent.com/17157860/54743709-2ef59e00-4bc5-11e9-8594-d59f8735f0ca.png)
![NatArndt](https://user-images.githubusercontent.com/17157860/54743710-2ef59e00-4bc5-11e9-8aa0-751b58f52ce7.png)
![NievesSande](https://user-images.githubusercontent.com/17157860/54743711-2ef59e00-4bc5-11e9-8f39-3a6067407758.png)
