### ISSUE TITLE
Zusätzliche Informationen

### ISSUE THREAD

**Issue by SandraBartsch** [AKSW/lswt2019.aksw.org#23]
bitte setze nochdie Infos zum DBpedia Meeting am 23.5. und zur LDK (20.-22.5) mit auf die LSWT-Seite.

13. DBpedia Community Meeting: https://wiki.dbpedia.org/meetings/Leipzig2019
 LDK Konferenz an der ULEI: http://2019.ldk-conf.org/

Das wurde so mit Micha besprochen.

**Comment by white-gecko** [comment]
Wie und wo soll ich das am besten unterbringen? @SandraBartsch @MichaelMartin

**Comment by JuliaHolze** [comment]
Im Introtext soll folgender Satz noch hinzugefügt werden: Das InfAI organisiert und unterstützt rundum den LSWT weitere Events. Verpassen Sie nicht die <a href=” http://2019.ldk-conf.org/”>Language, Data and Knowledge (LDK) Konferenz</a> (20.- 22. Mai) an der Universität Leipzig oder das <a href=”https://wiki.dbpedia.org/meetings/Leipzig2019”>13. DBpedia Community Meeting</a> am 23. Mai 2019 am Mediencampus Villa Ida.

**Comment by JuliaHolze** [comment]
The InfAI organizes and supports further events around the LSWT. Don't miss the <a href="http://2019.ldk-conf.org/">Language, Data and Knowledge (LDK) conference</a> (20-22 May) at the University of Leipzig or the <a href="https://wiki.dbpedia.org/meetings/Leipzig2019">13th DBpedia Community Meeting</a> on 23 May 2019 at the media campus Villa Ida.
