### ISSUE TITLE
Seite hat einen "Privacy Error"

### ISSUE THREAD

**Issue by seebi** [AKSW/lswt2019.aksw.org#34]
siehe screen

<img width="1305" alt="Screenshot 2019-03-21 at 10 43 35" src="https://user-images.githubusercontent.com/510452/54744070-4719ed00-4bc6-11e9-8598-0012820df94b.png">

<img width="1504" alt="Screenshot 2019-03-21 at 10 44 51" src="https://user-images.githubusercontent.com/510452/54744108-60229e00-4bc6-11e9-9278-f21a19c2da12.png">

**Comment by splattater** [comment]
Ich habe in der Infrastrukturgruppe des AKSW angefragt, warum das Zertifikat (letsencrypt) nicht erneuert wurde.

**Comment by JuliaHolze** [comment]
Simon hat das Problem gelöst.
